
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ClaseException", targetNamespace = "http://webServices/")
public class ClaseException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ClaseException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ClaseException_Exception(String message, ClaseException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ClaseException_Exception(String message, ClaseException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.ClaseException
     */
    public ClaseException getFaultInfo() {
        return faultInfo;
    }

}
