
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FechaInvalidaException", targetNamespace = "http://webServices/")
public class FechaInvalidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FechaInvalidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FechaInvalidaException_Exception(String message, FechaInvalidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FechaInvalidaException_Exception(String message, FechaInvalidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.FechaInvalidaException
     */
    public FechaInvalidaException getFaultInfo() {
        return faultInfo;
    }

}
