
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InstitucionException", targetNamespace = "http://webServices/")
public class InstitucionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InstitucionException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InstitucionException_Exception(String message, InstitucionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InstitucionException_Exception(String message, InstitucionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.InstitucionException
     */
    public InstitucionException getFaultInfo() {
        return faultInfo;
    }

}
