
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSContentController", targetNamespace = "http://webServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSContentController {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSContentController/postRequest", output = "http://webServices/WSContentController/postResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://webServices/WSContentController/post/Fault/IOException")
    })
    public void post(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        byte[] arg2)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webServices/WSContentController/sendReportsRequest", output = "http://webServices/WSContentController/sendReportsResponse")
    public void sendReports(
        @WebParam(name = "arg0", partName = "arg0")
        LogEntryWSArray arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSContentController/getRequest", output = "http://webServices/WSContentController/getResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://webServices/WSContentController/get/Fault/IOException")
    })
    public byte[] get(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws IOException_Exception
    ;

}
