
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebServiceClient(name = "WSContentControllerService", targetNamespace = "http://webServices/", wsdlLocation = "http://localhost:9129/entrenamosuy/contentController?wsdl")
public class WSContentControllerService
    extends Service
{

    private final static URL WSCONTENTCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCONTENTCONTROLLERSERVICE_EXCEPTION;
    private final static QName WSCONTENTCONTROLLERSERVICE_QNAME = new QName("http://webServices/", "WSContentControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9129/entrenamosuy/contentController?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONTENTCONTROLLERSERVICE_WSDL_LOCATION = url;
        WSCONTENTCONTROLLERSERVICE_EXCEPTION = e;
    }

    public WSContentControllerService() {
        super(__getWsdlLocation(), WSCONTENTCONTROLLERSERVICE_QNAME);
    }

    public WSContentControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONTENTCONTROLLERSERVICE_QNAME, features);
    }

    public WSContentControllerService(URL wsdlLocation) {
        super(wsdlLocation, WSCONTENTCONTROLLERSERVICE_QNAME);
    }

    public WSContentControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONTENTCONTROLLERSERVICE_QNAME, features);
    }

    public WSContentControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSContentControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSContentController
     */
    @WebEndpoint(name = "WSContentControllerPort")
    public WSContentController getWSContentControllerPort() {
        return super.getPort(new QName("http://webServices/", "WSContentControllerPort"), WSContentController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSContentController
     */
    @WebEndpoint(name = "WSContentControllerPort")
    public WSContentController getWSContentControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "WSContentControllerPort"), WSContentController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONTENTCONTROLLERSERVICE_EXCEPTION!= null) {
            throw WSCONTENTCONTROLLERSERVICE_EXCEPTION;
        }
        return WSCONTENTCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
