
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCuponeraControllerService", targetNamespace = "http://webServices/", wsdlLocation = "http://localhost:9129/entrenamosuy/cuponeraController?wsdl")
public class WSCuponeraControllerService
    extends Service
{

    private final static URL WSCUPONERACONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCUPONERACONTROLLERSERVICE_EXCEPTION;
    private final static QName WSCUPONERACONTROLLERSERVICE_QNAME = new QName("http://webServices/", "WSCuponeraControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9129/entrenamosuy/cuponeraController?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCUPONERACONTROLLERSERVICE_WSDL_LOCATION = url;
        WSCUPONERACONTROLLERSERVICE_EXCEPTION = e;
    }

    public WSCuponeraControllerService() {
        super(__getWsdlLocation(), WSCUPONERACONTROLLERSERVICE_QNAME);
    }

    public WSCuponeraControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCUPONERACONTROLLERSERVICE_QNAME, features);
    }

    public WSCuponeraControllerService(URL wsdlLocation) {
        super(wsdlLocation, WSCUPONERACONTROLLERSERVICE_QNAME);
    }

    public WSCuponeraControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCUPONERACONTROLLERSERVICE_QNAME, features);
    }

    public WSCuponeraControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCuponeraControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCuponeraController
     */
    @WebEndpoint(name = "WSCuponeraControllerPort")
    public WSCuponeraController getWSCuponeraControllerPort() {
        return super.getPort(new QName("http://webServices/", "WSCuponeraControllerPort"), WSCuponeraController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCuponeraController
     */
    @WebEndpoint(name = "WSCuponeraControllerPort")
    public WSCuponeraController getWSCuponeraControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "WSCuponeraControllerPort"), WSCuponeraController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCUPONERACONTROLLERSERVICE_EXCEPTION!= null) {
            throw WSCUPONERACONTROLLERSERVICE_EXCEPTION;
        }
        return WSCUPONERACONTROLLERSERVICE_WSDL_LOCATION;
    }

}
