
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCuponeraController", targetNamespace = "http://webServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    webservices.ObjectFactory.class
})
public interface WSCuponeraController {


    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSCuponeraController/buscarCuponerasRequest", output = "http://webServices/WSCuponeraController/buscarCuponerasResponse")
    public StringArray buscarCuponeras(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtCuponeraWS
     * @throws NoExisteCuponeraException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSCuponeraController/seleccionarCuponeraRequest", output = "http://webServices/WSCuponeraController/seleccionarCuponeraResponse", fault = {
        @FaultAction(className = NoExisteCuponeraException_Exception.class, value = "http://webServices/WSCuponeraController/seleccionarCuponera/Fault/NoExisteCuponeraException")
    })
    public DtCuponeraWS seleccionarCuponera(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoExisteCuponeraException_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSCuponeraController/getNombreCuponerasSinRecibosRequest", output = "http://webServices/WSCuponeraController/getNombreCuponerasSinRecibosResponse")
    public StringArray getNombreCuponerasSinRecibos();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSCuponeraController/getNombreCuponerasRequest", output = "http://webServices/WSCuponeraController/getNombreCuponerasResponse")
    public StringArray getNombreCuponeras();

}
