
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSUsuarioController", targetNamespace = "http://webServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    webservices.ObjectFactory.class
})
public interface WSUsuarioController {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws InstitucionException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/ingresarDatosUsuarioRequest", output = "http://webServices/WSUsuarioController/ingresarDatosUsuarioResponse", fault = {
        @FaultAction(className = InstitucionException_Exception.class, value = "http://webServices/WSUsuarioController/ingresarDatosUsuario/Fault/InstitucionException")
    })
    public int ingresarDatosUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        DtUsuarioWS arg0)
        throws InstitucionException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuarioController/seguirRequest", output = "http://webServices/WSUsuarioController/seguirResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/seguir/Fault/UsuarioNoExisteException")
    })
    public void seguir(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws CuponeraNoExisteException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuarioController/comprarCuponeraRequest", output = "http://webServices/WSUsuarioController/comprarCuponeraResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/comprarCuponera/Fault/UsuarioNoExisteException"),
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/comprarCuponera/Fault/CuponeraNoExisteException")
    })
    public void comprarCuponera(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DtFechaWS arg2)
        throws CuponeraNoExisteException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws UsuarioNoExisteException_Exception
     * @throws InstitucionException_Exception
     * @throws ClaseException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuarioController/valorarProfesorRequest", output = "http://webServices/WSUsuarioController/valorarProfesorResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/valorarProfesor/Fault/UsuarioNoExisteException"),
        @FaultAction(className = ClaseException_Exception.class, value = "http://webServices/WSUsuarioController/valorarProfesor/Fault/ClaseException"),
        @FaultAction(className = InstitucionException_Exception.class, value = "http://webServices/WSUsuarioController/valorarProfesor/Fault/InstitucionException")
    })
    public void valorarProfesor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4)
        throws ClaseException_Exception, InstitucionException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws UsuarioNoExisteException_Exception
     * @throws InstitucionException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuarioController/favoritearActividadRequest", output = "http://webServices/WSUsuarioController/favoritearActividadResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/favoritearActividad/Fault/UsuarioNoExisteException"),
        @FaultAction(className = InstitucionException_Exception.class, value = "http://webServices/WSUsuarioController/favoritearActividad/Fault/InstitucionException")
    })
    public void favoritearActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws InstitucionException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/pingRequest", output = "http://webServices/WSUsuarioController/pingResponse")
    public String ping();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/verificarIdentidadEmailRequest", output = "http://webServices/WSUsuarioController/verificarIdentidadEmailResponse")
    public boolean verificarIdentidadEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/verificarIdentidadNicknameRequest", output = "http://webServices/WSUsuarioController/verificarIdentidadNicknameResponse")
    public boolean verificarIdentidadNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuarioController/dejarDeSeguirRequest", output = "http://webServices/WSUsuarioController/dejarDeSeguirResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/dejarDeSeguir/Fault/UsuarioNoExisteException")
    })
    public void dejarDeSeguir(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.DtCapsula
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/obtenerUsuariosRequest", output = "http://webServices/WSUsuarioController/obtenerUsuariosResponse")
    public DtCapsula obtenerUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuarioWS
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/seleccionarUsuarioRequest", output = "http://webServices/WSUsuarioController/seleccionarUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/seleccionarUsuario/Fault/UsuarioNoExisteException")
    })
    public DtUsuarioWS seleccionarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuarioWS
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/seleccionarUsuarioEmailRequest", output = "http://webServices/WSUsuarioController/seleccionarUsuarioEmailResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/seleccionarUsuarioEmail/Fault/UsuarioNoExisteException")
    })
    public DtUsuarioWS seleccionarUsuarioEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuarioController/editarDatosBasicosRequest", output = "http://webServices/WSUsuarioController/editarDatosBasicosResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/editarDatosBasicos/Fault/UsuarioNoExisteException")
    })
    public void editarDatosBasicos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DtUsuarioWS arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.DtCapsula
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/obtenerInstitucionesRequest", output = "http://webServices/WSUsuarioController/obtenerInstitucionesResponse")
    public DtCapsula obtenerInstituciones();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtProfesorWS
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/seleccionarProfesorRequest", output = "http://webServices/WSUsuarioController/seleccionarProfesorResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/seleccionarProfesor/Fault/UsuarioNoExisteException")
    })
    public DtProfesorWS seleccionarProfesor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtSocioWS
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuarioController/seleccionarSocioRequest", output = "http://webServices/WSUsuarioController/seleccionarSocioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuarioController/seleccionarSocio/Fault/UsuarioNoExisteException")
    })
    public DtSocioWS seleccionarSocio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

}
